name: Actualizar Estadisticas de Valorant

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Dependencias
        run: npm install

      - name: Ejecutar Script de Actualización
        env:
          HENRIK_API_KEY: ${{ secrets.HENRIK_API_KEY }}
        run: node scripts/update.js

      - name: Verificar Cambios y Hacer Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add stats.json
          if git diff --staged --quiet; then
            echo "No se detectaron cambios en stats.json. Omitiendo commit."
          else
            git commit -m "chore: Actualización automática de estadísticas de jugadores [skip ci]"
            git push
          fi
